In [1]:
import rasterio as rs
import numpy as np

## **Importing & Reading of dataset**

In [2]:
with rs.open("T44RLT_20230225T051801_B04_10m.jp2") as f1,rs.open("T44RLT_20230225T051801_B08_10m.jp2") as f2:
    B04=f1.read(1)
    print(f"Width : {f1.width}")
    print(f"height : {f1.height}")
    print(f"CRS : {f1.crs}")
    print(f"Transform : {f1.transform}")
    print(f"COunt : {f1.count}")
    print(f"Array : {B04}")
    print(f"Max : {B04.max()}")
    print(f"Min : {B04.min()}")
    B08=f2.read(1)
    B08=B08.astype(np.float32)
    B04=B04.astype(np.float32)
    with np.errstate(divide='ignore', invalid='ignore'):
      B04=np.where(np.logical_and(B04==0,B08==0),np.nan,B04)
      B08=np.where(np.logical_and(B04==0,B08==0),np.nan,B08)
      NDVI= (B08 - B04) / (B08 + B04)

Width : 10980
height : 10980
CRS : EPSG:32644
Transform : | 10.00, 0.00, 300000.00|
| 0.00,-10.00, 3300000.00|
| 0.00, 0.00, 1.00|
COunt : 1
Array : [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Max : 0
Min : 0


In [3]:
NDVI.shape

(10980, 10980)

In [4]:
NDVI.mean()

np.float32(nan)

In [5]:
NDVI.max()

np.float32(nan)

In [6]:
NDVI.min()

np.float32(nan)

In [7]:
print(f" Pixels with NDVI>0.4 {(NDVI>0.4).sum()}")
print(f" Pixels with NDVI<0.2 {(NDVI<0.2).sum()}")
print(f" Pixels with NDVI<0 {(NDVI<0).sum()}")

 Pixels with NDVI>0.4 0
 Pixels with NDVI<0.2 0
 Pixels with NDVI<0 0


In [8]:
with rs.open("T44RLT_20230225T051801_B12_20m.jp2") as f3:
    B12=f3.read(1)
    print(f"Width : {f3.width}")
    print(f"height : {f3.height}")
    print(f"CRS : {f3.crs}")
    print(f"Transform : {f3.transform}")
    print(f"COunt : {f3.count}")
    print(f"Array : {B12}")
    print(f"Max : {B12.max()}")
    print(f"Min : {B12.min()}")

Width : 5490
height : 5490
CRS : EPSG:32644
Transform : | 20.00, 0.00, 300000.00|
| 0.00,-20.00, 3300000.00|
| 0.00, 0.00, 1.00|
COunt : 1
Array : [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Max : 0
Min : 0


In [9]:
import rasterio as rs
from rasterio.windows import Window
with rs.open("T44RLT_20230225T051801_B04_10m.jp2") as B04, rs.open("T44RLT_20230225T051801_B08_10m.jp2") as B08:
    test1_read=Window(0,0,256,256)
    B04_new=B04.read(1,window=test1_read)
    test2_read=Window(0,0,256,256)
    B08_new=B08.read(1,window=test2_read)
    print(B04.width)
    print(B04.height)
    print(B04.transform)
    print(B04.crs)
    print(B04_new.shape)
    print(B04_new.min())
    print(B04_new.max())

10980
10980
| 10.00, 0.00, 300000.00|
| 0.00,-10.00, 3300000.00|
| 0.00, 0.00, 1.00|
EPSG:32644
(256, 256)
891
6560


## **Bug Checked-All pixels valid or not**

In [10]:
NDVI_valid=NDVI.size-np.isnan(NDVI).sum()
print(NDVI_valid)

0


In [11]:
print(f" Pixels with NDVI>0.4 {(NDVI>0.4).sum()/NDVI_valid}")
print(f" Pixels with NDVI<0.2 {(NDVI<0.2).sum()/NDVI_valid}")
print(f" Pixels with NDVI<0 {(NDVI<0).sum()/NDVI_valid}")


/tmp/ipykernel_1125/3422978076.py:1: RuntimeWarning: invalid value encountered in scalar divide
  print(f" Pixels with NDVI>0.4 {(NDVI>0.4).sum()/NDVI_valid}")
/tmp/ipykernel_1125/3422978076.py:2: RuntimeWarning: invalid value encountered in scalar divide
  print(f" Pixels with NDVI<0.2 {(NDVI<0.2).sum()/NDVI_valid}")


 Pixels with NDVI>0.4 nan
 Pixels with NDVI<0.2 nan
 Pixels with NDVI<0 nan


/tmp/ipykernel_1125/3422978076.py:3: RuntimeWarning: invalid value encountered in scalar divide
  print(f" Pixels with NDVI<0 {(NDVI<0).sum()/NDVI_valid}")
